const propertyList = [
    {
        id:1,
        imgSrc:[
            "/propety-images/Jibhi.jpg",
            "/propety-images/Jibhi-1.jpg",
            "/propety-images/Jibhi-2.jpg",
            "/propety-images/Jibhi-3.jpg",
            "/propety-images/Jibhi-4.jpg"

        ],
        bedrooms:[
            "/propety-images/Jibhi-br-1.jpg",
            "/propety-images/Jibhi-br-2.jpg"
        ],
        name:"Jibhi, India",
        distance:"1,111 kilometers away",
        date:"1-6 jul",
        price:"6,846",
        category:"Cabins",
        rating:4.89,
        like:false,
    },
    {
        id:2,
        imgSrc:["/propety-images/shinano.jpg"],
        name:"Shinano, Kamiminochi District...",
        distance:"6,373 kilometers away",
        date:"1-4 apr",
        price:"40,035",
        category:"Cabins",
        rating:4.94,
        like:false,
        
    },
    {
        id:3,
        imgSrc:["/propety-images/sainji.jpg"],
        name:"Sainj, India",
        distance:"1,130 kilometers away",
        date:"11-16 feb",
        price:"2,281",
        category:"Cabins",
        rating:4.93,
        like:false,
    },
    {
        id:4,
        imgSrc:["/propety-images/hwachon.jpg"],
        name:"Hwachon-myeon, Hongcheon...",
        distance:"5,469 kilometers away",
        date:"1-6 jul",
        price:"6,635",
        category:"Cabins",
        rating:4.89,
        like:false,
    },
    {
        id:5,
        imgSrc:["/propety-images/Nago.jpg"],
        name:"Nago, Japan",
        distance:"5,534 kilometers away",
        date:"8-11 aug",
        price:"1,13,071",
        category:"Cabins",
        rating:5.0,
        like:false,
    },
    {
        id:6,
        imgSrc:["/propety-images/Mandremm.jpg"],
        name:"Mandrem, India",
        distance:"739 kilometers away",
        date:"3-8 jul",
        price:"7,417",
        category:"Cabins",
        rating:4.9,
        like:false,
    },
    {
        id:7,
        imgSrc:["/propety-images/siloti pant.jpg"],
        name:"Siloti Pant, India",
        distance:"1,009 kilometers away",
        date:"1-6 jul",
        price:"3,709",
        category:"Cabins",
        rating:4.92,
        like:false,
    },
    {
        id:8,
        imgSrc:["/propety-images/kecamatan.jpg"],
        name:"Kecamatan Banjar, Indonesia",
        distance:"5,689 kilometers away",
        date:"14-16 jan",
        price:"11,280",
        category:"Cabins",
        rating:4.91,
        like:false,
    },
    {
        id:9,
        imgSrc:["/propety-images/levallois-perret.jpg"],
        name:"Levallois, France",
        distance:"Stay with Annie Hrd at retreat",
        date:"9-14 feb",
        price:"8,271",
        category:"Rooms",
        rating:4.93,
        like:false,
    },
    {
        id:10,
        imgSrc:["/propety-images/vadholi.jpg"],
        name:"Vadholi, India",
        distance:"262 kilometers away",
        date:"17-22 mar",
        price:"12,450",
        category:"Amazing pools",
        rating:4.93,
        like:false,
    },
    {
        id:11,
        imgSrc:["/propety-images/sindun myeon.jpg"],
        name:"Sindun-myeon, Icheon-si, Sout...",
        distance:"5,410 kilometers away",
        date:"11-16 feb",
        price:"6,234",
        category:"OMG!",
        rating:4.84,
        like:false,
    },
    {
        id:12,
        imgSrc:["/propety-images/ericeira.jpg"],
        name:"Ericeira, Portugal",
        distance:"7,858 kilometers away",
        date:"5-13 apr",
        price:"11,558",
        category:"Windmills",
        rating:4.97,
        like:false,
    },
    {
        id:13,
        imgSrc:["/propety-images/Tambon hua.jpg"],
        name:"Tambon Hua Hin, Thailand",
        distance:"3,028",
        date:"5-10 mar",
        price:"39,956",
        category:"Design",
        rating:4.89,
        like:false,
    },

]

export default propertyList;